import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Card,Chip,Dialog,HelperText,Portal,Text,TextInput } from 'react-native-paper';
import { PlatformPage } from '@/components/superAdmin/PlatformPage';
import { AppButton } from '@/components/ui/AppButton';
import { EmptyState } from '@/components/ui/EmptyState';
import { getAdminAccessRequests,reviewAdminAccessRequest,type PlatformAdminRequest } from '@/features/superAdmin/api';

export default function AdminRequests(){const cache=useQueryClient();const[pending,setPending]=useState<{row:PlatformAdminRequest;approve:boolean}|null>(null);const[reason,setReason]=useState('');const query=useQuery({queryKey:['admin-access-requests'],queryFn:getAdminAccessRequests});const review=useMutation({mutationFn:()=>reviewAdminAccessRequest(pending!.row.id,pending!.approve,reason),onSuccess:async()=>{await cache.invalidateQueries({queryKey:['admin-access-requests']});setPending(null);setReason('')}});const labels:Record<string,string>={pending:'À valider',approved:'Approuvée',rejected:'Refusée',completed:'Compte créé',cancelled:'Annulée'};return <PlatformPage title="Demandes Administrateur">{!!query.error&&<HelperText type="error" visible>{query.error.message}</HelperText>}{(query.data??[]).map(row=><Card key={row.id} mode="outlined"><Card.Title title={row.full_name||row.email} subtitle={`${row.company_name} • ${new Date(row.created_at).toLocaleString('fr-CA')}`} right={()=><Chip style={{marginRight:12}}>{labels[row.status]??row.status}</Chip>}/><Card.Content><Text selectable>{row.email}</Text><Text>Première boutique : {row.store_name}</Text><Text>Pays : {row.country_code}</Text>{row.review_reason&&<Text style={{color:'#C92A2A'}}>Motif : {row.review_reason}</Text>}</Card.Content>{row.status==='pending'&&<Card.Actions><AppButton mode="text" textColor="#C92A2A" onPress={()=>setPending({row,approve:false})}>Refuser</AppButton><AppButton icon="check-decagram" onPress={()=>setPending({row,approve:true})}>Approuver</AppButton></Card.Actions>}</Card>)}{!query.isLoading&&!query.data?.length&&<EmptyState icon="account-check-outline" title="Aucune demande" message="Les demandes Employé vers Administrateur apparaîtront ici."/>}<Portal><Dialog visible={!!pending} onDismiss={()=>setPending(null)}><Dialog.Title>{pending?.approve?'Approuver cette demande ?':'Refuser cette demande ?'}</Dialog.Title><Dialog.Content style={{gap:10}}><Text>{pending?.row.email}</Text>{!pending?.approve&&<TextInput mode="outlined" label="Motif obligatoire" value={reason} onChangeText={setReason} multiline/>}{!!review.error&&<HelperText type="error" visible>{review.error.message}</HelperText>}</Dialog.Content><Dialog.Actions><AppButton mode="text" onPress={()=>setPending(null)}>Annuler</AppButton><AppButton buttonColor={pending?.approve?undefined:'#C92A2A'} loading={review.isPending} disabled={review.isPending||(!pending?.approve&&reason.trim().length<3)} onPress={()=>review.mutate()}>{pending?.approve?'Approuver':'Refuser'}</AppButton></Dialog.Actions></Dialog></Portal></PlatformPage>}
