import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useMemo,useState } from 'react';
import { Alert,StyleSheet,View } from 'react-native';
import { Card,Chip,HelperText,IconButton,Text,TextInput } from 'react-native-paper';
import { SelectField } from '@/components/forms/SelectField';
import { AdminPage } from '@/components/ui/AdminPage';
import { AppButton } from '@/components/ui/AppButton';
import { useAuth } from '@/features/auth/AuthProvider';
import { getCustomers } from '@/features/customers/api';
import { cancelCustomerOrder,createCustomerOrder,deliverCustomerOrder,getCustomerOrders,type CustomerOrder } from '@/features/orders/api';
import { getSaleStock } from '@/features/sales/api';
import { useCurrency } from '@/features/currency/CurrencyProvider';
import { formatQuantity,parseDecimal } from '@/utils/number';

type DraftLine={key:string;productId:string;variantId:string|null;name:string;quantity:number;price:number};
const labels={confirmed:'Confirmée',partial:'Partielle',fulfilled:'Livrée',cancelled:'Annulée'};

export default function OrdersScreen(){
  const{membership}=useAuth();const{formatMoney}=useCurrency();const cache=useQueryClient();const company=membership?.companyId??'',store=membership?.storeId??'';
  const[creating,setCreating]=useState(false);const[selected,setSelected]=useState<CustomerOrder|null>(null);const[customerId,setCustomerId]=useState<string|null>(null);const[stockKey,setStockKey]=useState<string|null>(null);const[quantity,setQuantity]=useState('1');const[deposit,setDeposit]=useState('0');const[note,setNote]=useState('');const[lines,setLines]=useState<DraftLine[]>([]);const[deliveries,setDeliveries]=useState<Record<string,string>>({});const[paidNow,setPaidNow]=useState('0');const[method,setMethod]=useState<string|null>('cash');const[formError,setFormError]=useState('');
  const orders=useQuery({queryKey:['customer-orders',company,store],queryFn:()=>getCustomerOrders(company,store),enabled:!!store});const customers=useQuery({queryKey:['customers',company],queryFn:()=>getCustomers(company),enabled:!!company});const stock=useQuery({queryKey:['sale-stock',company,store],queryFn:()=>getSaleStock(company,store,false),enabled:!!store});
  const total=useMemo(()=>lines.reduce((sum,line)=>sum+line.quantity*line.price,0),[lines]);
  const refresh=async()=>Promise.all([cache.invalidateQueries({queryKey:['customer-orders']}),cache.invalidateQueries({queryKey:['sales']}),cache.invalidateQueries({queryKey:['sale-stock']}),cache.invalidateQueries({queryKey:['cash-transactions']}),cache.invalidateQueries({queryKey:['cash-summary']})]);
  const create=useMutation({mutationFn:()=>createCustomerOrder(store,customerId!,lines.map(x=>({productId:x.productId,variantId:x.variantId,quantity:x.quantity})),parseDecimal(deposit)||0,note),onSuccess:async()=>{await refresh();setCreating(false);setLines([]);setCustomerId(null);setDeposit('0');setNote('')}});
  const deliver=useMutation({mutationFn:()=>deliverCustomerOrder(selected!.id,Object.entries(deliveries).filter(([,q])=>parseDecimal(q)>0).map(([orderItemId,q])=>({orderItemId,quantity:parseDecimal(q)})),method!,parseDecimal(paidNow)||0),onSuccess:async()=>{await refresh();setSelected(null);setDeliveries({});setPaidNow('0')}});
  const cancel=useMutation({mutationFn:()=>cancelCustomerOrder(selected!.id,true),onSuccess:async()=>{await refresh();setSelected(null)}});
  const add=()=>{const item=stock.data?.find(x=>`${x.productId}:${x.variantId??''}`===stockKey);const qty=parseDecimal(quantity);if(!item)return setFormError('Sélectionnez un produit.');if(!(qty>0))return setFormError('Quantité invalide.');setFormError('');setLines(current=>[...current,{key:`${item.productId}:${item.variantId??''}:${Date.now()}`,productId:item.productId,variantId:item.variantId,name:item.name,quantity:qty,price:item.salePrice}]);setStockKey(null);setQuantity('1')};

  if(selected){
    const remaining=selected.customer_order_items.reduce((sum,x)=>sum+(Number(x.quantity)-Number(x.delivered_quantity))*Number(x.unit_price),0);const deliverable=selected.status==='confirmed'||selected.status==='partial';
    const invalidQuantity=selected.customer_order_items.some(x=>{const value=parseDecimal(deliveries[x.id]);return Number.isFinite(value)&&value>Number(x.quantity)-Number(x.delivered_quantity)});const chosen=selected.customer_order_items.reduce((sum,x)=>sum+Math.max(0,parseDecimal(deliveries[x.id])||0)*Number(x.unit_price),0);
    return <AdminPage title={selected.reference}><Card mode="contained"><Card.Title title={selected.customer?.name??'Client'} subtitle={`Reste à livrer : ${formatMoney(remaining)}`}/></Card>{selected.customer_order_items.map(item=>{const left=Number(item.quantity)-Number(item.delivered_quantity);return <Card key={item.id} mode="outlined"><Card.Title title={item.variant?`${item.product?.name} • ${item.variant.name}`:item.product?.name??'Produit'} subtitle={`${formatQuantity(item.delivered_quantity)} livré sur ${formatQuantity(item.quantity)}`}/><Card.Content><TextInput mode="outlined" label={`À livrer (max. ${formatQuantity(left)})`} value={deliveries[item.id]??''} onChangeText={v=>setDeliveries(c=>({...c,[item.id]:v}))} keyboardType="decimal-pad" disabled={!deliverable||left<=0}/></Card.Content></Card>})}<Card mode="contained"><Card.Title title={`Livraison : ${formatMoney(chosen)}`} subtitle={`Acompte disponible : ${formatMoney(selected.deposit_remaining)}`}/></Card>{deliverable&&<><SelectField label="Mode du complément" value={method} onChange={setMethod} options={[{label:'Espèces',value:'cash'},{label:'Orange Money',value:'mobile_money'}]}/><TextInput mode="outlined" label="Montant payé maintenant" value={paidNow} onChangeText={setPaidNow} keyboardType="decimal-pad"/></>}{invalidQuantity&&<HelperText type="error" visible>Une quantité dépasse le reste à livrer.</HelperText>}<HelperText type="error" visible={!!deliver.error||!!cancel.error}>{deliver.error?.message??cancel.error?.message}</HelperText><View style={styles.actions}>{deliverable&&<AppButton style={styles.grow} icon="truck-check" loading={deliver.isPending} disabled={chosen<=0||!method||invalidQuantity||deliver.isPending} onPress={()=>deliver.mutate()}>Valider la livraison</AppButton>}{selected.status==='confirmed'&&<AppButton mode="outlined" textColor="#B42318" icon="close-circle" loading={cancel.isPending} onPress={()=>Alert.alert('Annuler la commande','L’acompte sera remboursé dans la caisse.',[{text:'Garder',style:'cancel'},{text:'Annuler et rembourser',style:'destructive',onPress:()=>cancel.mutate()}])}>Annuler</AppButton>}</View></AdminPage>
  }
  if(creating){const depositValue=parseDecimal(deposit)||0;return <AdminPage title="Nouvelle commande"><SelectField label="Client" value={customerId} onChange={setCustomerId} options={(customers.data??[]).filter(x=>x.is_active).map(x=>({label:x.name,value:x.id}))}/><Card mode="outlined"><Card.Title title="Ajouter un article"/><Card.Content style={styles.stack}><SelectField label="Produit" value={stockKey} onChange={setStockKey} options={(stock.data??[]).map(x=>({label:`${x.name} · ${formatMoney(x.salePrice)}`,value:`${x.productId}:${x.variantId??''}`}))}/><TextInput mode="outlined" label="Quantité" value={quantity} onChangeText={setQuantity} keyboardType="decimal-pad"/><HelperText type="error" visible={!!formError}>{formError}</HelperText><AppButton mode="outlined" icon="plus" onPress={add}>Ajouter</AppButton></Card.Content></Card>{lines.map(line=><Card key={line.key} mode="contained"><Card.Title title={line.name} subtitle={`${formatQuantity(line.quantity)} × ${formatMoney(line.price)}`} right={()=> <IconButton icon="delete" onPress={()=>setLines(x=>x.filter(y=>y.key!==line.key))}/>}/></Card>)}<TextInput mode="outlined" label="Acompte reçu" value={deposit} onChangeText={setDeposit} keyboardType="decimal-pad"/><TextInput mode="outlined" label="Note (facultatif)" value={note} onChangeText={setNote} multiline/><Card mode="contained"><Card.Title title={`Total : ${formatMoney(total)}`}/></Card>{depositValue<0&&<HelperText type="error" visible>L’acompte ne peut pas être négatif.</HelperText>}<HelperText type="error" visible={!!create.error}>{create.error?.message}</HelperText><AppButton icon="check" loading={create.isPending} disabled={!customerId||!lines.length||depositValue<0||depositValue>total} onPress={()=>create.mutate()}>Enregistrer la commande</AppButton></AdminPage>}
  return <AdminPage title="Commandes clients" action={<AppButton compact icon="plus" onPress={()=>setCreating(true)}>Nouvelle</AppButton>}>{orders.isLoading&&<Text>Chargement…</Text>}{!!orders.error&&<HelperText type="error" visible>{orders.error.message}</HelperText>}{orders.data?.length===0&&<Card mode="outlined"><Card.Title title="Aucune commande" subtitle="Créez une commande client, puis livrez-la en une ou plusieurs fois."/></Card>}{orders.data?.map(order=><Card key={order.id} mode="outlined" onPress={()=>{setSelected(order);setDeliveries({})}}><Card.Title title={`${order.reference} • ${order.customer?.name??'Client'}`} subtitle={`${formatMoney(order.total)} · Acompte restant ${formatMoney(order.deposit_remaining)}`} right={()=> <Chip style={styles.chip}>{labels[order.status]}</Chip>}/></Card>)}</AdminPage>
}
const styles=StyleSheet.create({stack:{gap:10},actions:{flexDirection:'row',flexWrap:'wrap',gap:10},grow:{flexGrow:1},chip:{marginRight:10}});
