import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Card,Chip,HelperText,Text,TextInput } from 'react-native-paper';
import { SelectField } from '@/components/forms/SelectField';
import { AdminPage } from '@/components/ui/AdminPage';
import { AppButton } from '@/components/ui/AppButton';
import { useAuth } from '@/features/auth/AuthProvider';
import { createTicket,getMyTickets } from '@/features/support/api';
export default function SupportScreen(){const{membership}=useAuth();const cache=useQueryClient();const company=membership?.companyId??'';const[open,setOpen]=useState(false);const[subject,setSubject]=useState('');const[description,setDescription]=useState('');const[priority,setPriority]=useState<string|null>('normal');const query=useQuery({queryKey:['my-support-tickets',company],queryFn:()=>getMyTickets(company),enabled:!!company});const create=useMutation({mutationFn:()=>createTicket(company,subject,description,priority!),onSuccess:async()=>{await cache.invalidateQueries({queryKey:['my-support-tickets']});setOpen(false);setSubject('');setDescription('')}});return <AdminPage title="Assistance" action={<AppButton compact icon="plus" onPress={()=>setOpen(true)}>Nouveau</AppButton>}>{open&&<Card mode="contained"><Card.Title title="Contacter le support StockMaster"/><Card.Content style={{gap:10}}><TextInput mode="outlined" label="Sujet" value={subject} onChangeText={setSubject}/><TextInput mode="outlined" label="Décrivez précisément le problème" value={description} onChangeText={setDescription} multiline numberOfLines={5}/><SelectField label="Priorité" value={priority} onChange={setPriority} options={[{label:'Faible',value:'low'},{label:'Normale',value:'normal'},{label:'Haute',value:'high'},{label:'Urgente',value:'urgent'}]}/><HelperText type="error" visible={!!create.error}>{create.error?.message}</HelperText><AppButton loading={create.isPending} disabled={subject.trim().length<3||description.trim().length<10||!priority} onPress={()=>create.mutate()}>Envoyer au support</AppButton></Card.Content></Card>}{(query.data??[]).map(ticket=><Card key={ticket.id} mode="outlined"><Card.Title title={ticket.subject} subtitle={new Date(ticket.created_at).toLocaleString('fr-CA')} right={()=> <Chip style={{marginRight:12}}>{ticket.status}</Chip>}/><Card.Content><Text>{ticket.description}</Text>{!!ticket.resolution&&<Text style={{fontWeight:'700',marginTop:10}}>Réponse : {ticket.resolution}</Text>}</Card.Content></Card>)}<HelperText type="error" visible={!!query.error}>{query.error?.message}</HelperText></AdminPage>}
