import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { router } from 'expo-router';
import { Card,HelperText,TextInput } from 'react-native-paper';
import { AdminPage } from '@/components/ui/AdminPage';
import { AppButton } from '@/components/ui/AppButton';
import { SelectField } from '@/components/forms/SelectField';
import { useAuth } from '@/features/auth/AuthProvider';
import { getStockLevels } from '@/features/inventory/api';
import { transferStock } from '@/features/operations/api';
import { parseDecimal,formatQuantity } from '@/utils/number';

export default function TransfersScreen(){const{membership,stores}=useAuth();const qc=useQueryClient();const company=membership?.companyId??'';const source=membership?.storeId??'';const levels=useQuery({queryKey:['stock-levels',company,source],queryFn:()=>getStockLevels(company,undefined,source),enabled:!!source});const[productId,setProductId]=useState<string|null>(null);const[target,setTarget]=useState<string|null>(null);const[quantity,setQuantity]=useState('1');const selected=levels.data?.find(item=>item.product_id===productId&&!item.product_variant_id);const mutation=useMutation({mutationFn:()=>transferStock(source,target!,productId!,parseDecimal(quantity)),onSuccess:async()=>{setProductId(null);setTarget(null);setQuantity('1');await qc.invalidateQueries({queryKey:['stock-levels',company]});router.replace('/stock' as never)}});return <AdminPage title="Transfert entre boutiques"><Card mode="contained"><Card.Title title="Boutique source" subtitle={membership?.storeName??'Boutique active'}/></Card><SelectField label="Boutique destination" value={target} onChange={setTarget} options={stores.filter(item=>item.storeId!==source).map(item=>({label:item.storeName,value:item.storeId}))}/><SelectField label="Produit" value={productId} onChange={setProductId} options={(levels.data??[]).filter(item=>!item.product_variant_id&&Number(item.quantity)>0).map(item=>({label:`${item.product?.name??'Produit'} - stock ${formatQuantity(item.quantity)}`,value:item.product_id}))}/><TextInput mode="outlined" label="Quantité à transférer" keyboardType="decimal-pad" value={quantity} onChangeText={setQuantity}/>{selected&&<HelperText type="info" visible>Disponible : {formatQuantity(selected.quantity)}</HelperText>}{!!mutation.error&&<HelperText type="error" visible>{mutation.error.message}</HelperText>}<AppButton icon="swap-horizontal" loading={mutation.isPending} disabled={!target||!productId||!(parseDecimal(quantity)>0)||parseDecimal(quantity)>Number(selected?.quantity??0)} onPress={()=>mutation.mutate()}>Confirmer le transfert</AppButton></AdminPage>}
