import { useQuery } from '@tanstack/react-query';
import { StyleSheet,View } from 'react-native';
import { Card,HelperText,Icon,Text,useTheme } from 'react-native-paper';
import { AdminPage } from '@/components/ui/AdminPage';
import { EmptyState } from '@/components/ui/EmptyState';
import { getSecurityEvents } from '@/features/account/security';
const labels:Record<string,string>={login:'Connexion',mfa_enabled:'2FA activée',mfa_disabled:'2FA désactivée',global_logout:'Déconnexion globale'};
export default function SecurityHistory(){const theme=useTheme();const query=useQuery({queryKey:['security-events'],queryFn:getSecurityEvents});return <AdminPage title="Journal de sécurité">{!!query.error&&<HelperText type="error" visible>{query.error.message}</HelperText>}{query.data?.map(event=><Card key={event.id} mode="outlined"><Card.Content style={styles.row}><View style={[styles.icon,{backgroundColor:theme.colors.surfaceVariant}]}><Icon source={event.event_type==='login'?'login':'shield-check-outline'} size={25} color={theme.colors.primary}/></View><View style={styles.copy}><Text variant="titleMedium" style={styles.bold}>{labels[event.event_type]??event.event_type}</Text><Text style={{color:theme.colors.onSurfaceVariant}}>{event.device_label??'Appareil inconnu'}</Text><Text variant="bodySmall" style={{color:theme.colors.onSurfaceVariant}}>{new Date(event.created_at).toLocaleString('fr-FR')}</Text></View></Card.Content></Card>)}{!query.isLoading&&!query.data?.length&&<EmptyState icon="shield-search" title="Aucun événement" message="Les prochaines connexions seront enregistrées ici."/>}</AdminPage>}
const styles=StyleSheet.create({row:{flexDirection:'row',alignItems:'center',gap:12},icon:{width:44,height:44,borderRadius:14,alignItems:'center',justifyContent:'center'},copy:{flex:1,minWidth:0,gap:2},bold:{fontWeight:'800'}});
