import type { BottomTabBarProps } from '@react-navigation/bottom-tabs';
import { router } from 'expo-router';
import { Image } from 'expo-image';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, useWindowDimensions, View } from 'react-native';
import { Divider, Icon, Text, Tooltip, useTheme } from 'react-native-paper';
import { useAuth } from '@/features/auth/AuthProvider';
import { design } from '@/constants/design';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

type Link={label:string;icon:string;path:string;route:string;emphasis?:boolean};
const groups:{label:string;links:Link[]}[]=[
  {label:'Principal',links:[{label:'Accueil',icon:'view-dashboard-outline',path:'/(admin)',route:'index'},{label:'Ventes',icon:'cart-outline',path:'/sales',route:'sales'},{label:'Stock',icon:'warehouse',path:'/stock',route:'stock'},{label:'Caisse',icon:'wallet-outline',path:'/cash',route:'cash'},{label:'Clients',icon:'account-group-outline',path:'/customers',route:'customers'},{label:'Rapports',icon:'chart-box-outline',path:'/reports',route:'reports'}]},
  {label:'Autres',links:[{label:'Tous les outils',icon:'dots-grid',path:'/more',route:'more'}]},
];

function NavItem({link,active,collapsed=false,mobile=false}:{link:Link;active:boolean;collapsed?:boolean;mobile?:boolean}){const theme=useTheme();const content=<Pressable accessibilityRole="button" accessibilityLabel={link.label} onPress={()=>router.navigate(link.path as never)} style={({pressed})=>[styles.item,collapsed&&styles.itemCollapsed,mobile&&styles.bottomItem,!mobile&&link.emphasis&&styles.emphasis,active&&mobile&&styles.bottomItemActive,active&&!mobile&&!link.emphasis&&{backgroundColor:theme.colors.primaryContainer},pressed&&styles.pressed]}><Icon source={link.icon} size={mobile?22:23} color={!mobile&&link.emphasis?'#FFFFFF':active?design.colors.brand:theme.colors.onSurfaceVariant}/>{!collapsed&&<Text numberOfLines={1} style={[styles.itemText,mobile&&styles.bottomLabel,!mobile&&link.emphasis&&styles.emphasisText,active&&{color:design.colors.brand}]}>{link.label}</Text>}</Pressable>;return collapsed?<Tooltip title={link.label}>{content}</Tooltip>:content}

export function AdminNavigation({state}:BottomTabBarProps){const{width}=useWindowDimensions();const insets=useSafeAreaInsets();const theme=useTheme();const{membership}=useAuth();const desktop=width>=960;const[collapsed,setCollapsed]=useState(false);const current=state.routes[state.index]?.name??'index';if(!desktop){const allLinks:Link[]=[{label:'Accueil',icon:'home-outline',path:'/(admin)',route:'index'},{label:'Ventes',icon:'cart-outline',path:'/sales',route:'sales'},{label:'Stock',icon:'warehouse',path:'/stock',route:'stock'},{label:'Caisse',icon:'wallet-outline',path:'/cash',route:'cash'},{label:'Clients',icon:'account-group-outline',path:'/customers',route:'customers'},{label:'Rapports',icon:'chart-box-outline',path:'/reports',route:'reports'},{label:'Plus',icon:'dots-grid',path:'/more',route:'more'}];const links=width<430?allLinks.filter(link=>['index','sales','stock','cash','more'].includes(link.route)):allLinks;const primaryRoutes=new Set(['index','sales','stock','cash','customers','reports']);return <View style={[styles.bottom,{paddingBottom:Math.max(insets.bottom,6),backgroundColor:theme.colors.surface,borderTopColor:theme.colors.outlineVariant}]}>{links.map(link=><View key={link.label} style={styles.mobileItem}><NavItem link={link} active={current===link.route||(link.route==='more'&&!primaryRoutes.has(current))} mobile/></View>)}</View>}
  return <View style={[styles.sidebar,collapsed&&styles.sidebarCollapsed,{backgroundColor:theme.colors.surface,borderRightColor:theme.colors.outlineVariant}]}><View style={styles.brand}><Image source={require('../../../assets/images/stockmaster-icon.png')} style={styles.logo} contentFit="cover"/>{!collapsed&&<View style={styles.brandCopy}><Text variant="titleLarge" style={styles.brandTitle}>StockMaster</Text><Text variant="bodySmall" numberOfLines={1}>{membership?.companyName}</Text><Text variant="labelSmall" numberOfLines={1}>{membership?.storeName}</Text></View>}</View><Divider/>
  <ScrollView style={styles.groups} contentContainerStyle={styles.groupsContent} showsVerticalScrollIndicator={false}>{groups.map(group=><View key={group.label} style={styles.group}>{!collapsed&&<Text variant="labelSmall" style={styles.groupLabel}>{group.label.toUpperCase()}</Text>}{group.links.map(link=><NavItem key={link.label} link={link} active={current===link.route} collapsed={collapsed}/>)}</View>)}</ScrollView><Divider/><Pressable onPress={()=>setCollapsed(value=>!value)} style={[styles.item,collapsed&&styles.itemCollapsed]}><Icon source={collapsed?'chevron-double-right':'chevron-double-left'} size={21}/>{!collapsed&&<Text style={styles.itemText}>Réduire le menu</Text>}</Pressable></View>
}

const styles=StyleSheet.create({sidebar:{width:264,padding:14,borderRightWidth:1,gap:12},sidebarCollapsed:{width:78},brand:{minHeight:58,flexDirection:'row',alignItems:'center',gap:11},logo:{width:46,height:46,borderRadius:14},brandCopy:{flex:1},brandTitle:{fontWeight:'900',color:design.colors.brand},groups:{flex:1},groupsContent:{gap:12,paddingBottom:8},group:{gap:4},groupLabel:{color:design.colors.muted,fontWeight:'800',paddingHorizontal:12,marginBottom:2},item:{minHeight:44,borderRadius:design.radius.small,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:11},itemCollapsed:{justifyContent:'center',paddingHorizontal:0},itemText:{fontWeight:'700'},emphasis:{backgroundColor:design.colors.brand},emphasisText:{color:'#FFFFFF'},pressed:{opacity:.72},bottom:{minHeight:64,flexDirection:'row',alignItems:'stretch',borderTopWidth:1,paddingHorizontal:2,paddingTop:5},bottomItem:{minHeight:54,paddingHorizontal:1,gap:2,flexDirection:'column',justifyContent:'center',borderRadius:12},bottomItemActive:{backgroundColor:design.colors.brandSoft},bottomLabel:{fontSize:9,textAlign:'center',fontWeight:'700'},mobileItem:{flex:1,minWidth:0},});
