import { useMutation,useQueryClient } from '@tanstack/react-query';
import { Image } from 'expo-image';
import { router } from 'expo-router';
import { StyleSheet,View } from 'react-native';
import { Card,HelperText,Icon,Text,useTheme } from 'react-native-paper';
import { AppButton } from '@/components/ui/AppButton';
import { useAuth } from '@/features/auth/AuthProvider';
import { useSubscription } from '@/features/subscriptions/SubscriptionProvider';
import { supabase } from '@/services/supabase/client';

export default function BillingWelcome(){const theme=useTheme();const cache=useQueryClient();const{membership}=useAuth();const{subscription,refreshSubscription}=useSubscription();const companyId=membership?.companyId??'';const confirm=useMutation({mutationFn:async(choice:'trial'|'subscription')=>{if(!companyId)throw new Error('Entreprise indisponible. Reconnectez-vous puis réessayez.');const{error}=await supabase.rpc('confirm_billing_onboarding',{p_company_id:companyId,p_choice:choice});if(error)throw new Error(error.message);return choice},onSuccess:choice=>{cache.setQueryData(['billing-onboarding',companyId],false);void refreshSubscription().catch(()=>undefined);if(choice==='trial'){router.replace('/(admin)' as never);return;}router.replace({pathname:'/(auth)/login' as never,params:{notice:'Votre abonnement est bien activé. Connectez-vous pour démarrer avec votre forfait.'}});}});const days=subscription?.expiresAt?Math.max(0,Math.ceil((new Date(subscription.expiresAt).getTime()-Date.now())/86400000)):14;return <View style={[styles.screen,{backgroundColor:theme.colors.background}]}><View style={styles.page}><Image source={require('../../../assets/images/stockmaster-icon.png')} style={styles.logo} contentFit="cover"/><Text variant="headlineMedium" style={styles.title}>Bienvenue sur StockMaster</Text><Text style={styles.center}>Votre adresse email est confirmée. Choisissez maintenant comment démarrer avant d’accéder à votre espace.</Text><Card mode="contained" style={{backgroundColor:theme.colors.primaryContainer}}><Card.Title title={`Essai gratuit de ${days} jours`} subtitle="Aucune carte bancaire requise" left={()=><Icon source="gift-outline" size={30}/>}/><Card.Content><Text>Testez les fonctions incluses dans le forfait de démarrage. Vos données seront conservées à la fin de l’essai.</Text></Card.Content><Card.Actions><AppButton icon="check-circle-outline" loading={confirm.isPending&&confirm.variables==='trial'} disabled={confirm.isPending} onPress={()=>confirm.mutate('trial')}>Activer mon essai gratuit</AppButton></Card.Actions></Card><Card mode="outlined"><Card.Title title="Choisir un abonnement" subtitle="Orange Money ou carte bancaire" left={()=><Icon source="credit-card-outline" size={30}/>}/><Card.Content><Text>Comparez les forfaits et choisissez immédiatement celui qui correspond à votre entreprise.</Text></Card.Content><Card.Actions><AppButton mode="outlined" icon="arrow-right" loading={confirm.isPending&&confirm.variables==='subscription'} disabled={confirm.isPending} onPress={()=>confirm.mutate('subscription')}>Voir les abonnements</AppButton></Card.Actions></Card>{!!confirm.error&&<HelperText type="error" visible>{confirm.error.message}</HelperText>}</View></View>}
const styles=StyleSheet.create({screen:{flex:1},page:{width:'100%',maxWidth:640,alignSelf:'center',padding:20,gap:18,justifyContent:'center',flex:1},logo:{width:90,height:90,borderRadius:26,alignSelf:'center'},title:{fontWeight:'800',textAlign:'center'},center:{textAlign:'center'}});
