create table public.support_tickets(
  id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,
  subject text not null,description text not null,priority text not null default 'normal' check(priority in('low','normal','high','urgent')),
  status text not null default 'open' check(status in('open','in_progress','resolved','closed')),created_by uuid not null references public.profiles(id),
  assigned_to uuid references public.profiles(id),resolution text,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create index support_tickets_status_idx on public.support_tickets(status,priority,created_at desc);create trigger touch_updated_at before update on public.support_tickets for each row execute function public.touch_updated_at();
alter table public.support_tickets enable row level security;
create policy support_tickets_read on public.support_tickets for select to authenticated using(public.is_super_admin() or (public.belongs_to_company(company_id) and public.is_company_admin(company_id)));
grant select on public.support_tickets to authenticated;revoke insert,update,delete on public.support_tickets from anon,authenticated;
create or replace function public.create_support_ticket(p_company_id uuid,p_subject text,p_description text,p_priority text default 'normal') returns uuid language plpgsql security definer set search_path=public as $$declare v_id uuid;begin if not public.belongs_to_company(p_company_id) or not public.is_company_admin(p_company_id) then raise exception 'Acces refuse';end if;if length(trim(p_subject))<3 or length(trim(p_description))<10 or p_priority not in('low','normal','high','urgent') then raise exception 'Ticket invalide';end if;insert into support_tickets(company_id,subject,description,priority,created_by) values(p_company_id,trim(p_subject),trim(p_description),p_priority,auth.uid()) returning id into v_id;return v_id;end $$;
create or replace function public.update_support_ticket(p_ticket_id uuid,p_status text,p_resolution text default null) returns void language plpgsql security definer set search_path=public as $$begin if not public.is_super_admin() then raise exception 'Acces Super Admin requis';end if;if p_status not in('open','in_progress','resolved','closed') then raise exception 'Statut invalide';end if;update support_tickets set status=p_status,resolution=nullif(trim(p_resolution),''),assigned_to=auth.uid() where id=p_ticket_id;if not found then raise exception 'Ticket introuvable';end if;end $$;
grant execute on function public.create_support_ticket(uuid,text,text,text) to authenticated;grant execute on function public.update_support_ticket(uuid,text,text) to authenticated;revoke execute on function public.create_support_ticket(uuid,text,text,text) from anon;revoke execute on function public.update_support_ticket(uuid,text,text) from anon;

create or replace function public.super_admin_company_health() returns table(company_id uuid,company_name text,is_active boolean,last_sale_at timestamptz,last_activity_at timestamptz,error_count_7d bigint,fatal_count_7d bigint,open_tickets bigint,subscription_status text) language sql stable security definer set search_path=public as $$select c.id,c.name,c.is_active,(select max(created_at) from sales where company_id=c.id),(select max(created_at) from audit_logs where company_id=c.id),(select count(*) from app_error_events where company_id=c.id and created_at>=now()-interval '7 days'),(select count(*) from app_error_events where company_id=c.id and severity='fatal' and created_at>=now()-interval '7 days'),(select count(*) from support_tickets where company_id=c.id and status in('open','in_progress')),(select s.status::text from subscriptions s where s.company_id=c.id order by s.created_at desc limit 1) from companies c where public.is_super_admin() order by 7 desc,6 desc,2$$;
grant execute on function public.super_admin_company_health() to authenticated;revoke execute on function public.super_admin_company_health() from anon;
