create sequence if not exists public.customer_order_reference_seq;
create table public.customer_orders(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,store_id uuid not null references public.stores(id) on delete cascade,customer_id uuid not null references public.customers(id) on delete restrict,reference text not null unique,status text not null default 'confirmed' check(status in ('confirmed','partial','fulfilled','cancelled')),total numeric(12,2) not null,deposit_amount numeric(12,2) not null default 0,deposit_remaining numeric(12,2) not null default 0,note text,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.customer_order_items(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,order_id uuid not null references public.customer_orders(id) on delete cascade,product_id uuid not null references public.products(id),product_variant_id uuid references public.product_variants(id),quantity numeric(14,3) not null check(quantity>0),delivered_quantity numeric(14,3) not null default 0,unit_price numeric(12,2) not null,created_at timestamptz not null default now());
create index customer_orders_store_status_idx on public.customer_orders(store_id,status,created_at desc);create trigger touch_updated_at before update on public.customer_orders for each row execute function public.touch_updated_at();
alter table public.customer_orders enable row level security;alter table public.customer_order_items enable row level security;
create policy customer_orders_read on public.customer_orders for select to authenticated using(public.belongs_to_company(company_id) and public.can_access_store(company_id,store_id) and public.has_permission(company_id,'sales.read'));
create policy customer_order_items_read on public.customer_order_items for select to authenticated using(public.belongs_to_company(company_id) and public.has_permission(company_id,'sales.read'));
grant select on public.customer_orders,public.customer_order_items to authenticated;revoke insert,update,delete on public.customer_orders,public.customer_order_items from anon,authenticated;

create or replace function public.create_customer_order(p_store_id uuid,p_customer_id uuid,p_items jsonb,p_deposit numeric default 0,p_note text default null,p_operation_id uuid default gen_random_uuid()) returns uuid language plpgsql security definer set search_path=public as $$
declare v_company uuid;v_order uuid;v_item jsonb;v_product record;v_qty numeric;v_price numeric;v_total numeric:=0;v_cash uuid;
begin select company_id into v_company from stores where id=p_store_id;if v_company is null or not public.can_access_store(v_company,p_store_id) or not public.has_active_subscription(v_company) or not (public.is_company_admin(v_company) or public.has_permission(v_company,'sales.write')) then raise exception 'Commande refusée';end if;if not exists(select 1 from customers where id=p_customer_id and company_id=v_company and is_active) then raise exception 'Client invalide';end if;if p_items is null or jsonb_array_length(p_items)=0 then raise exception 'Commande vide';end if;
  perform public.lock_operation(p_operation_id);select id into v_order from customer_orders where id=p_operation_id;if v_order is not null then return v_order;end if;v_order:=p_operation_id;
  for v_item in select value from jsonb_array_elements(p_items) loop v_qty:=(v_item->>'quantity')::numeric;select p.id,coalesce(pv.sale_price,p.sale_price) price into v_product from products p left join product_variants pv on pv.id=nullif(v_item->>'variantId','')::uuid and pv.product_id=p.id and pv.is_active where p.id=(v_item->>'productId')::uuid and p.company_id=v_company and p.store_id=p_store_id and p.is_active and (nullif(v_item->>'variantId','') is null or pv.id is not null);if v_product.id is null or v_qty<=0 then raise exception 'Article commande invalide';end if;v_total:=v_total+v_product.price*v_qty;end loop;
  if p_deposit<0 or p_deposit>v_total then raise exception 'Acompte invalide';end if;insert into customer_orders(id,company_id,store_id,customer_id,reference,total,deposit_amount,deposit_remaining,note,created_by) values(v_order,v_company,p_store_id,p_customer_id,'CMD-'||to_char(now(),'YYYYMMDD')||'-'||lpad(nextval('customer_order_reference_seq')::text,5,'0'),v_total,p_deposit,p_deposit,nullif(trim(p_note),''),auth.uid());
  for v_item in select value from jsonb_array_elements(p_items) loop v_qty:=(v_item->>'quantity')::numeric;select p.id,coalesce(pv.sale_price,p.sale_price) price into v_product from products p left join product_variants pv on pv.id=nullif(v_item->>'variantId','')::uuid and pv.product_id=p.id where p.id=(v_item->>'productId')::uuid;insert into customer_order_items(company_id,order_id,product_id,product_variant_id,quantity,unit_price) values(v_company,v_order,v_product.id,nullif(v_item->>'variantId','')::uuid,v_qty,v_product.price);end loop;
  if p_deposit>0 then insert into cash_transactions(company_id,store_id,transaction_type,designation,amount,source,payment_method,operation_id,created_by) values(v_company,p_store_id,'deposit','Acompte commande '||v_order,p_deposit,'customer_order','cash',p_operation_id,auth.uid()) returning id into v_cash;end if;return v_order;end $$;

create or replace function public.deliver_customer_order(p_order_id uuid,p_items jsonb,p_payment_method text,p_amount_paid_now numeric default 0,p_operation_id uuid default gen_random_uuid()) returns uuid language plpgsql security definer set search_path=public as $$
declare v_order customer_orders%rowtype;v_input jsonb;v_line customer_order_items%rowtype;v_sale_items jsonb:='[]';v_sale record;v_delivery_total numeric:=0;v_apply_deposit numeric;v_paid numeric;
begin select * into v_order from customer_orders where id=p_order_id for update;if not found or v_order.status not in ('confirmed','partial') then raise exception 'Commande non livrable';end if;if not public.can_access_store(v_order.company_id,v_order.store_id) or not (public.is_company_admin(v_order.company_id) or public.has_permission(v_order.company_id,'sales.write')) then raise exception 'Livraison refusée';end if;
  for v_input in select value from jsonb_array_elements(p_items) loop select * into v_line from customer_order_items where id=(v_input->>'orderItemId')::uuid and order_id=p_order_id for update;if not found or (v_input->>'quantity')::numeric<=0 or v_line.delivered_quantity+(v_input->>'quantity')::numeric>v_line.quantity then raise exception 'Quantité livrée invalide';end if;v_delivery_total:=v_delivery_total+(v_input->>'quantity')::numeric*v_line.unit_price;v_sale_items:=v_sale_items||jsonb_build_array(jsonb_build_object('productId',v_line.product_id,'variantId',v_line.product_variant_id,'quantity',(v_input->>'quantity')::numeric,'discount',0));end loop;
  v_apply_deposit:=least(v_order.deposit_remaining,v_delivery_total);v_paid:=least(v_delivery_total,greatest(0,p_amount_paid_now)+v_apply_deposit);select * into v_sale from create_sale_v2(v_order.store_id,p_payment_method,v_sale_items,v_order.customer_id,v_paid,p_operation_id);
  if least(p_amount_paid_now,v_delivery_total-v_apply_deposit)<=0 then delete from cash_transactions where sale_id=v_sale.sale_id;else update cash_transactions set amount=least(p_amount_paid_now,v_delivery_total-v_apply_deposit) where sale_id=v_sale.sale_id;end if;
  for v_input in select value from jsonb_array_elements(p_items) loop update customer_order_items set delivered_quantity=delivered_quantity+(v_input->>'quantity')::numeric where id=(v_input->>'orderItemId')::uuid;end loop;
  update customer_orders set deposit_remaining=deposit_remaining-v_apply_deposit,status=case when not exists(select 1 from customer_order_items where order_id=p_order_id and delivered_quantity<quantity) then 'fulfilled' else 'partial' end where id=p_order_id;return v_sale.sale_id;end $$;
grant execute on function public.create_customer_order(uuid,uuid,jsonb,numeric,text,uuid) to authenticated;grant execute on function public.deliver_customer_order(uuid,jsonb,text,numeric,uuid) to authenticated;

create or replace function public.cancel_customer_order(p_order_id uuid,p_refund_deposit boolean default true,p_operation_id uuid default gen_random_uuid()) returns void language plpgsql security definer set search_path=public as $$
declare v_order customer_orders%rowtype;
begin
  select * into v_order from customer_orders where id=p_order_id for update;
  if not found or v_order.status='cancelled' then raise exception 'Commande introuvable ou deja annulee';end if;
  if v_order.status<>'confirmed' or exists(select 1 from customer_order_items where order_id=p_order_id and delivered_quantity>0) then raise exception 'Une commande deja livree ne peut pas etre annulee';end if;
  if not public.can_access_store(v_order.company_id,v_order.store_id) or not (public.is_company_admin(v_order.company_id) or public.has_permission(v_order.company_id,'sales.write')) then raise exception 'Annulation refusee';end if;
  perform public.lock_operation(p_operation_id);
  if p_refund_deposit and v_order.deposit_remaining>0 then
    insert into cash_transactions(company_id,store_id,transaction_type,designation,amount,source,payment_method,operation_id,created_by)
    values(v_order.company_id,v_order.store_id,'withdrawal','Remboursement acompte '||v_order.reference,v_order.deposit_remaining,'customer_order_refund','cash',p_operation_id,auth.uid());
  end if;
  update customer_orders set status='cancelled',deposit_remaining=case when p_refund_deposit then 0 else deposit_remaining end where id=p_order_id;
end $$;
revoke execute on function public.create_customer_order(uuid,uuid,jsonb,numeric,text,uuid) from anon;
revoke execute on function public.deliver_customer_order(uuid,jsonb,text,numeric,uuid) from anon;
revoke execute on function public.cancel_customer_order(uuid,boolean,uuid) from anon;
grant execute on function public.cancel_customer_order(uuid,boolean,uuid) to authenticated;
