import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import type { ReceiptBranding } from './branding';
import { printHtmlDocument } from '@/utils/printHtml';

type PaymentReceipt = ReceiptBranding & { title:string;party:string;amount:number;balanceBefore:number;balanceAfter:number;date:string;reference:string;note?:string|null;partyLabel?:string;amountLabel?:string;showBalances?:boolean };
const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' })[c]!);
const html=(receipt:PaymentReceipt,money:(value:number)=>string)=>{
  const accent=/^#[0-9A-Fa-f]{6}$/.test(receipt.accentColor)?receipt.accentColor:'#084B50';
  return `<!doctype html><html><head><meta charset="utf-8"><style>@page{margin:24px}*{box-sizing:border-box}body{font-family:Arial;margin:0;color:#17212b}header{text-align:center;border-bottom:3px solid ${accent};padding:18px}${receipt.logoUrl?'.logo{max-width:82px;max-height:82px;object-fit:contain;margin-bottom:8px}':''}h1{color:${accent};margin:5px}.business{font-size:20px;font-weight:800}.contact{max-width:520px;margin:7px auto;color:#667085;font-size:11px;line-height:1.6}.box{margin:28px 0;padding:22px;border:1px solid #d0d5dd;border-radius:14px}.row{display:flex;justify-content:space-between;gap:20px;padding:8px 0}.row b{text-align:right}.total{font-size:24px;font-weight:800;color:${accent};border-top:2px solid ${accent};margin-top:8px;padding-top:14px}footer{text-align:center;color:#667085;margin-top:40px;line-height:1.7}</style></head><body><header>${receipt.logoUrl?`<img class="logo" src="${escape(receipt.logoUrl)}" alt="Logo">`:''}<div class="business">${escape(receipt.company)}</div>${receipt.store?`<div>${escape(receipt.store)}</div>`:''}<div class="contact">${[receipt.address,receipt.phone,receipt.email].filter(Boolean).map(escape).join(' • ')}</div><h2>${escape(receipt.title)}</h2><div>${escape(receipt.reference)}</div></header><div class="box"><div class="row"><span>${escape(receipt.partyLabel??'Bénéficiaire')}</span><b>${escape(receipt.party)}</b></div><div class="row"><span>Date</span><b>${escape(new Date(receipt.date).toLocaleString('fr-FR'))}</b></div>${receipt.issuedBy?`<div class="row"><span>Enregistré par</span><b>${escape(receipt.issuedBy)}</b></div>`:''}${receipt.showBalances===false?'':`<div class="row"><span>Solde avant</span><b>${escape(money(receipt.balanceBefore))}</b></div>`}<div class="row total"><span>${escape(receipt.amountLabel??'Montant payé')}</span><span>${escape(money(receipt.amount))}</span></div>${receipt.showBalances===false?'':`<div class="row"><span>Solde après</span><b>${escape(money(receipt.balanceAfter))}</b></div>`}${receipt.note?`<p>Note : ${escape(receipt.note)}</p>`:''}</div><footer>${receipt.footer?`${escape(receipt.footer)}<br>`:''}Document généré par StockMaster</footer></body></html>`;
};
export async function printPaymentReceipt(receipt:PaymentReceipt,money:(value:number)=>string){await printHtmlDocument(html(receipt,money),receipt.title);}
export async function sharePaymentReceipt(receipt:PaymentReceipt,money:(value:number)=>string){const file=await Print.printToFileAsync({html:html(receipt,money)});if(!(await Sharing.isAvailableAsync()))throw new Error('Le partage n’est pas disponible sur cet appareil.');await Sharing.shareAsync(file.uri,{mimeType:'application/pdf',dialogTitle:receipt.title});}
